version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  server:
    depends_on:
      - mysql
    container_name: server
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
