version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_TCP_PORT: 3306
    expose:
      - 3306

  server:
    depends_on:
     - mysql
    container_name: server
    build:
      context: .
    ports:
      - 3000:3000

volumes:
  mysql_data:

